#!/usr/bin/env python

"""
dope score calculation
"""

from modeller import *
from modeller.scripts import complete_pdb


def DOPE(pdb_file):
    """Calculate DOPE score given a PDB structure.

    Parameters
    ----------
    pdb_file : string
        direction to a PDB file

    Returns
    -------
    score : float
        DOPE score
    """

    # set up env
    env = environ()
    env.libs.topology.read(file='$(LIB)/top_heav.lib')
    env.libs.parameters.read(file='$(LIB)/par.lib')

    # Read a model previously generated by Modeller's automodel class
    mdl = complete_pdb(env, pdb_file)

    # Select all atoms in the first chain
    atmsel = selection(mdl.chains[0])

    score = atmsel.assess_dope()

    return score
